### ISSUE TITLE
Names

### ISSUE THREAD

**Issue by AFAgarap** [andreinamiling/practice-programming-problems#1]
Please write the proper filenames & class names now that you have uploaded your solutions to GitHub.
Example: For problem #1, `NumberPyramid.java`. So, in it, it would be "public class NumberPyramid {"

**Comment by AFAgarap** [comment]
For problem #2, it would be `ArctanSeries.java`
For problem #3, it would be `Kriti.java`

**Comment by AFAgarap** [comment]
@andreinamiling You still did not fix this issue.

**Comment by andreinamiling** [comment]
Can I fix it through mobile? Anw, I'll fix it later.

**Comment by AFAgarap** [comment]
Okay, good job.
